[package]
name = "w9pt-integration-test"
version = "0.0.0"
publish = false
edition = "2024"
rust-version = "1.94.1"
license = "Apache-2.0"

[dependencies]
axum = { version = "=0.8.9", default-features = false, features = ["http1", "tokio", "ws"] }
aws-sdk-s3 = { version = "=1.145.0", default-features = false, features = ["default-https-client", "rt-tokio"] }
futures-util = { version = "=0.3.34", default-features = false, features = ["sink", "std"] }
tokio = { version = "1.53.1", features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tokio-tungstenite = { version = "=0.29.0", default-features = false, features = ["connect", "handshake"] }
w9pt = { path = "../crates/w9pt" }
w9pt-fs = { path = "../crates/w9pt-fs" }
w9pt-fs-state = { path = "../crates/w9pt-fs-state" }
w9pt-fs-state-postgres = { path = "../crates/w9pt-fs-state-postgres" }
w9pt-fs-storage = { path = "../crates/w9pt-fs-storage", features = ["compression-lz4", "encryption-aes-siv"] }
w9pt-fs-storage-s3 = { path = "../crates/w9pt-fs-storage-s3" }
sea-orm = { version = "=1.1.20", default-features = false, features = ["sqlx-postgres", "runtime-tokio"] }

[[bin]]
name = "w9pt-tcp-seaweedfs-test"
path = "src/main.rs"

[[bin]]
name = "w9pt-websocket-seaweedfs-test"
path = "src/bin/websocket.rs"

[lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[lints.clippy]
all = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"

[workspace]
