//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "w9pt_fs_state_opens"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub filesystem_id: Vec<u8>,
    pub open_id: Vec<u8>,
    pub inode_id: Vec<u8>,
    pub client_incarnation_id: Vec<u8>,
    pub access: i16,
    pub append: bool,
    pub retained_inode_generation: Decimal,
    pub record_revision: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    FilesystemId,
    OpenId,
    InodeId,
    ClientIncarnationId,
    Access,
    Append,
    RetainedInodeGeneration,
    RecordRevision,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    FilesystemId,
    OpenId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (Vec<u8>, Vec<u8>);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    W9ptFsStateInodes,
    W9ptFsStateLocks,
    W9ptFsStateOpenPins,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::FilesystemId => ColumnType::VarBinary(StringLen::None).def(),
            Self::OpenId => ColumnType::VarBinary(StringLen::None).def(),
            Self::InodeId => ColumnType::VarBinary(StringLen::None).def(),
            Self::ClientIncarnationId => ColumnType::VarBinary(StringLen::None).def(),
            Self::Access => ColumnType::SmallInteger.def(),
            Self::Append => ColumnType::Boolean.def(),
            Self::RetainedInodeGeneration => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::RecordRevision => ColumnType::Decimal(Some((20u32, 0u32))).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::W9ptFsStateInodes => Entity::belongs_to(super::w9pt_fs_state_inodes::Entity)
                .from((Column::FilesystemId, Column::InodeId))
                .to((
                    super::w9pt_fs_state_inodes::Column::FilesystemId,
                    super::w9pt_fs_state_inodes::Column::InodeId,
                ))
                .into(),
            Self::W9ptFsStateLocks => Entity::has_many(super::w9pt_fs_state_locks::Entity).into(),
            Self::W9ptFsStateOpenPins => {
                Entity::has_one(super::w9pt_fs_state_open_pins::Entity).into()
            }
        }
    }
}

impl Related<super::w9pt_fs_state_inodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateInodes.def()
    }
}

impl Related<super::w9pt_fs_state_locks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateLocks.def()
    }
}

impl Related<super::w9pt_fs_state_open_pins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateOpenPins.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
