//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "w9pt_fs_state_change_keys"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub filesystem_id: Vec<u8>,
    pub revision: Decimal,
    pub ordinal: i32,
    pub family_tag: i16,
    pub component_a: Option<Vec<u8>>,
    pub component_b: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    FilesystemId,
    Revision,
    Ordinal,
    FamilyTag,
    ComponentA,
    ComponentB,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    FilesystemId,
    Revision,
    Ordinal,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (Vec<u8>, Decimal, i32);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    W9ptFsStateChangeCommits,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::FilesystemId => ColumnType::VarBinary(StringLen::None).def(),
            Self::Revision => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::Ordinal => ColumnType::Integer.def(),
            Self::FamilyTag => ColumnType::SmallInteger.def(),
            Self::ComponentA => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::ComponentB => ColumnType::VarBinary(StringLen::None).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::W9ptFsStateChangeCommits => {
                Entity::belongs_to(super::w9pt_fs_state_change_commits::Entity)
                    .from((Column::FilesystemId, Column::Revision))
                    .to((
                        super::w9pt_fs_state_change_commits::Column::FilesystemId,
                        super::w9pt_fs_state_change_commits::Column::Revision,
                    ))
                    .into()
            }
        }
    }
}

impl Related<super::w9pt_fs_state_change_commits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateChangeCommits.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
