//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "w9pt_fs_state_writer_lease_operations"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub filesystem_id: Vec<u8>,
    pub lease_operation_id: Vec<u8>,
    pub operation_kind: i16,
    pub request_fingerprint: Vec<u8>,
    pub outcome_tag: i16,
    pub grant_scope_id: Option<Vec<u8>>,
    pub grant_holder_id: Option<Vec<u8>>,
    pub grant_lease_id: Option<Vec<u8>>,
    pub grant_deadline_tick: Option<Decimal>,
    pub grant_fencing_token: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    FilesystemId,
    LeaseOperationId,
    OperationKind,
    RequestFingerprint,
    OutcomeTag,
    GrantScopeId,
    GrantHolderId,
    GrantLeaseId,
    GrantDeadlineTick,
    GrantFencingToken,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    FilesystemId,
    LeaseOperationId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (Vec<u8>, Vec<u8>);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::FilesystemId => ColumnType::VarBinary(StringLen::None).def(),
            Self::LeaseOperationId => ColumnType::VarBinary(StringLen::None).def(),
            Self::OperationKind => ColumnType::SmallInteger.def(),
            Self::RequestFingerprint => ColumnType::VarBinary(StringLen::None).def(),
            Self::OutcomeTag => ColumnType::SmallInteger.def(),
            Self::GrantScopeId => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::GrantHolderId => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::GrantLeaseId => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::GrantDeadlineTick => ColumnType::Decimal(Some((20u32, 0u32))).def().null(),
            Self::GrantFencingToken => ColumnType::Decimal(Some((20u32, 0u32))).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
