//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "w9pt_fs_state_inodes"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub filesystem_id: Vec<u8>,
    pub inode_id: Vec<u8>,
    pub qid_path: Decimal,
    pub record_revision: Decimal,
    pub mode: i32,
    pub owner: Vec<u8>,
    pub group_id: Vec<u8>,
    pub accessed_seconds: i64,
    pub accessed_nanoseconds: i32,
    pub modified_seconds: i64,
    pub modified_nanoseconds: i32,
    pub changed_seconds: i64,
    pub changed_nanoseconds: i32,
    pub created_seconds: i64,
    pub created_nanoseconds: i32,
    pub logical_size: Decimal,
    pub link_count: Decimal,
    pub inode_generation: Decimal,
    pub kind: i16,
    pub content_file_id: Option<Vec<u8>>,
    pub data_generation: Option<Decimal>,
    pub content_generation: Option<Decimal>,
    pub content_logical_size: Option<Decimal>,
    pub content_manifest_key: Option<String>,
    pub content_manifest_digest: Option<Vec<u8>>,
    pub content_storage_method: Option<i16>,
    pub directory_generation: Option<Decimal>,
    pub directory_parent_inode_id: Option<Vec<u8>>,
    pub symlink_target: Option<Vec<u8>>,
    pub device_major: Option<i64>,
    pub device_minor: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    FilesystemId,
    InodeId,
    QidPath,
    RecordRevision,
    Mode,
    Owner,
    GroupId,
    AccessedSeconds,
    AccessedNanoseconds,
    ModifiedSeconds,
    ModifiedNanoseconds,
    ChangedSeconds,
    ChangedNanoseconds,
    CreatedSeconds,
    CreatedNanoseconds,
    LogicalSize,
    LinkCount,
    InodeGeneration,
    Kind,
    ContentFileId,
    DataGeneration,
    ContentGeneration,
    ContentLogicalSize,
    ContentManifestKey,
    ContentManifestDigest,
    ContentStorageMethod,
    DirectoryGeneration,
    DirectoryParentInodeId,
    SymlinkTarget,
    DeviceMajor,
    DeviceMinor,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    FilesystemId,
    InodeId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (Vec<u8>, Vec<u8>);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    W9ptFsStateFilesystemRecords,
    SelfRef,
    W9ptFsStateLocks,
    W9ptFsStateOpenPins,
    W9ptFsStateOpens,
    W9ptFsStateOrphans,
    W9ptFsStateXattrStaging,
    W9ptFsStateXattrs,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::FilesystemId => ColumnType::VarBinary(StringLen::None).def(),
            Self::InodeId => ColumnType::VarBinary(StringLen::None).def(),
            Self::QidPath => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::RecordRevision => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::Mode => ColumnType::Integer.def(),
            Self::Owner => ColumnType::VarBinary(StringLen::None).def(),
            Self::GroupId => ColumnType::VarBinary(StringLen::None).def(),
            Self::AccessedSeconds => ColumnType::BigInteger.def(),
            Self::AccessedNanoseconds => ColumnType::Integer.def(),
            Self::ModifiedSeconds => ColumnType::BigInteger.def(),
            Self::ModifiedNanoseconds => ColumnType::Integer.def(),
            Self::ChangedSeconds => ColumnType::BigInteger.def(),
            Self::ChangedNanoseconds => ColumnType::Integer.def(),
            Self::CreatedSeconds => ColumnType::BigInteger.def(),
            Self::CreatedNanoseconds => ColumnType::Integer.def(),
            Self::LogicalSize => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::LinkCount => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::InodeGeneration => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::Kind => ColumnType::SmallInteger.def(),
            Self::ContentFileId => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::DataGeneration => ColumnType::Decimal(Some((20u32, 0u32))).def().null(),
            Self::ContentGeneration => ColumnType::Decimal(Some((20u32, 0u32))).def().null(),
            Self::ContentLogicalSize => ColumnType::Decimal(Some((20u32, 0u32))).def().null(),
            Self::ContentManifestKey => ColumnType::Text.def().null(),
            Self::ContentManifestDigest => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::ContentStorageMethod => ColumnType::SmallInteger.def().null(),
            Self::DirectoryGeneration => ColumnType::Decimal(Some((20u32, 0u32))).def().null(),
            Self::DirectoryParentInodeId => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::SymlinkTarget => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::DeviceMajor => ColumnType::BigInteger.def().null(),
            Self::DeviceMinor => ColumnType::BigInteger.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::W9ptFsStateFilesystemRecords => {
                Entity::has_many(super::w9pt_fs_state_filesystem_records::Entity).into()
            }
            Self::SelfRef => Entity::belongs_to(Entity)
                .from((Column::FilesystemId, Column::DirectoryParentInodeId))
                .to((Column::FilesystemId, Column::InodeId))
                .into(),
            Self::W9ptFsStateLocks => Entity::has_many(super::w9pt_fs_state_locks::Entity).into(),
            Self::W9ptFsStateOpenPins => {
                Entity::has_many(super::w9pt_fs_state_open_pins::Entity).into()
            }
            Self::W9ptFsStateOpens => Entity::has_many(super::w9pt_fs_state_opens::Entity).into(),
            Self::W9ptFsStateOrphans => {
                Entity::has_one(super::w9pt_fs_state_orphans::Entity).into()
            }
            Self::W9ptFsStateXattrStaging => {
                Entity::has_many(super::w9pt_fs_state_xattr_staging::Entity).into()
            }
            Self::W9ptFsStateXattrs => Entity::has_many(super::w9pt_fs_state_xattrs::Entity).into(),
        }
    }
}

impl Related<super::w9pt_fs_state_filesystem_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateFilesystemRecords.def()
    }
}

impl Related<super::w9pt_fs_state_locks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateLocks.def()
    }
}

impl Related<super::w9pt_fs_state_open_pins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateOpenPins.def()
    }
}

impl Related<super::w9pt_fs_state_opens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateOpens.def()
    }
}

impl Related<super::w9pt_fs_state_orphans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateOrphans.def()
    }
}

impl Related<super::w9pt_fs_state_xattr_staging::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateXattrStaging.def()
    }
}

impl Related<super::w9pt_fs_state_xattrs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateXattrs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
