//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "w9pt_fs_state_locks"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub filesystem_id: Vec<u8>,
    pub inode_id: Vec<u8>,
    pub lock_id: Vec<u8>,
    pub range_start: Decimal,
    pub range_end: Option<Decimal>,
    pub kind: i16,
    pub owner_client_incarnation_id: Vec<u8>,
    pub owner_open_id: Vec<u8>,
    pub lock_generation: Decimal,
    pub record_revision: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    FilesystemId,
    InodeId,
    LockId,
    RangeStart,
    RangeEnd,
    Kind,
    OwnerClientIncarnationId,
    OwnerOpenId,
    LockGeneration,
    RecordRevision,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    FilesystemId,
    InodeId,
    LockId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (Vec<u8>, Vec<u8>, Vec<u8>);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    W9ptFsStateInodes,
    W9ptFsStateOpens,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::FilesystemId => ColumnType::VarBinary(StringLen::None).def(),
            Self::InodeId => ColumnType::VarBinary(StringLen::None).def(),
            Self::LockId => ColumnType::VarBinary(StringLen::None).def(),
            Self::RangeStart => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::RangeEnd => ColumnType::Decimal(Some((20u32, 0u32))).def().null(),
            Self::Kind => ColumnType::SmallInteger.def(),
            Self::OwnerClientIncarnationId => ColumnType::VarBinary(StringLen::None).def(),
            Self::OwnerOpenId => ColumnType::VarBinary(StringLen::None).def(),
            Self::LockGeneration => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::RecordRevision => ColumnType::Decimal(Some((20u32, 0u32))).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::W9ptFsStateInodes => Entity::belongs_to(super::w9pt_fs_state_inodes::Entity)
                .from((Column::FilesystemId, Column::InodeId))
                .to((
                    super::w9pt_fs_state_inodes::Column::FilesystemId,
                    super::w9pt_fs_state_inodes::Column::InodeId,
                ))
                .into(),
            Self::W9ptFsStateOpens => Entity::belongs_to(super::w9pt_fs_state_opens::Entity)
                .from((Column::FilesystemId, Column::InodeId, Column::OwnerOpenId))
                .to((
                    super::w9pt_fs_state_opens::Column::FilesystemId,
                    super::w9pt_fs_state_opens::Column::InodeId,
                    super::w9pt_fs_state_opens::Column::OpenId,
                ))
                .into(),
        }
    }
}

impl Related<super::w9pt_fs_state_inodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateInodes.def()
    }
}

impl Related<super::w9pt_fs_state_opens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateOpens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
