//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "w9pt_fs_state_writer_fences"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub filesystem_id: Vec<u8>,
    pub writer_scope_id: Vec<u8>,
    pub greatest_fencing_token: Decimal,
    pub active_holder_id: Option<Vec<u8>>,
    pub active_lease_id: Option<Vec<u8>>,
    pub active_deadline_tick: Option<Decimal>,
    pub active_record_revision: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    FilesystemId,
    WriterScopeId,
    GreatestFencingToken,
    ActiveHolderId,
    ActiveLeaseId,
    ActiveDeadlineTick,
    ActiveRecordRevision,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    FilesystemId,
    WriterScopeId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (Vec<u8>, Vec<u8>);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::FilesystemId => ColumnType::VarBinary(StringLen::None).def(),
            Self::WriterScopeId => ColumnType::VarBinary(StringLen::None).def(),
            Self::GreatestFencingToken => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::ActiveHolderId => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::ActiveLeaseId => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::ActiveDeadlineTick => ColumnType::Decimal(Some((20u32, 0u32))).def().null(),
            Self::ActiveRecordRevision => ColumnType::Decimal(Some((20u32, 0u32))).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
