//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "w9pt_fs_state_xattrs"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub filesystem_id: Vec<u8>,
    pub inode_id: Vec<u8>,
    pub name: Vec<u8>,
    pub value: Vec<u8>,
    pub record_revision: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    FilesystemId,
    InodeId,
    Name,
    Value,
    RecordRevision,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    FilesystemId,
    InodeId,
    Name,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (Vec<u8>, Vec<u8>, Vec<u8>);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    W9ptFsStateInodes,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::FilesystemId => ColumnType::VarBinary(StringLen::None).def(),
            Self::InodeId => ColumnType::VarBinary(StringLen::None).def(),
            Self::Name => ColumnType::VarBinary(StringLen::None).def(),
            Self::Value => ColumnType::VarBinary(StringLen::None).def(),
            Self::RecordRevision => ColumnType::Decimal(Some((20u32, 0u32))).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::W9ptFsStateInodes => Entity::belongs_to(super::w9pt_fs_state_inodes::Entity)
                .from((Column::FilesystemId, Column::InodeId))
                .to((
                    super::w9pt_fs_state_inodes::Column::FilesystemId,
                    super::w9pt_fs_state_inodes::Column::InodeId,
                ))
                .into(),
        }
    }
}

impl Related<super::w9pt_fs_state_inodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateInodes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
