//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "w9pt_fs_state_change_commits"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub filesystem_id: Vec<u8>,
    pub revision: Decimal,
    pub origin_kind: i16,
    pub origin_id: Vec<u8>,
    pub key_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    FilesystemId,
    Revision,
    OriginKind,
    OriginId,
    KeyCount,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    FilesystemId,
    Revision,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (Vec<u8>, Decimal);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    W9ptFsStateChangeKeys,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::FilesystemId => ColumnType::VarBinary(StringLen::None).def(),
            Self::Revision => ColumnType::Decimal(Some((20u32, 0u32))).def(),
            Self::OriginKind => ColumnType::SmallInteger.def(),
            Self::OriginId => ColumnType::VarBinary(StringLen::None).def(),
            Self::KeyCount => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::W9ptFsStateChangeKeys => {
                Entity::has_many(super::w9pt_fs_state_change_keys::Entity).into()
            }
        }
    }
}

impl Related<super::w9pt_fs_state_change_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::W9ptFsStateChangeKeys.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
